name 'infranodes'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures infranodes'
long_description 'Installs/Configures infranodes'
version '0.2.0'

depends 'chef-ingredient'
depends 'wombat'
depends 'push-jobs'
depends 'hostsfile'
depends 'line'
