language: ruby
cache: bundler

sudo: false

branches:
  only:
    - master

before_install:
  - gem update --system
  - gem --version
  - gem uninstall bundler -a -x -I
  - rvm @global do gem uninstall bundler -a -x -I
  - gem install bundler
  - bundle --version
  - rm -f .bundle/config
rvm:
  - 2.3.3
  - 2.4.0
  - ruby-head

allow_failures:
  - rvm: ruby-head

script:
  - bundle exec rake spec
