language: ruby
cache: bundler

sudo: false

branches:
  only:
    - master

before_install:
  - gem --version

rvm:
  - 2.3
  - 2.4
  - ruby-head

allow_failures:
  - rvm: ruby-head

script:
  - bundle exec rake spec
