name 'chefy-server'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures delivery'
long_description 'Installs/Configures delivery'
version '0.1.0'

depends 'apt'
depends 'chef-ingredient', '>= 0.18.5'
depends 'hostsfile'
depends 'line'
depends 'wombat'
