name 'wombat'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures wombat'
long_description 'Installs/Configures wombat'
version '0.2.0'

depends 'hostsfile'
depends 'apt'
depends 'chef-ingredient'
depends 'sudo'
depends 'line'
