name 'mock-data'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures mock-data'
long_description 'Installs/Configures mock-data'
version '0.1.0'
