source 'https://supermarket.chef.io'

metadata

cookbook 'delivery_build', git: "https://github.com/cheeseplus/delivery_build"
cookbook 'delivery-base', git: "https://github.com/chef-cookbooks/delivery-base"
cookbook 'mock-data', path: 'test/fixtures/cookbooks/mock-data'