name 'build-node'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures build-node'
long_description 'Installs/Configures build-node'
version '0.1.0'

depends 'apt'
depends 'chef-sugar'
depends 'delivery-base'
depends 'delivery_build'
depends 'hostsfile'
depends 'line'
depends 'wombat'
