---
driver:
  name: vagrant
  customize:
    cpus: 2
    memory: 2048
  synced_folders:
    - ["../../", "/tmp/wombat"]

provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[git::default]
      - recipe[packman::default]
      - recipe[wombat::default]
    attributes:
      demo:
        build-nodes: 1
        versions:
          automate: current-0.4.553
          chefdk: stable-0.16.28
      wombat:
        packer:
          aws:
            secret_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
            access_key: <%= ENV['AWS_ACCESS_KEY_ID'] %>
            keypair: andre
      packman:
        checksums:
          0.10.1: 7d51fc5db19d02bbf32278a8116830fae33a3f9bd4440a58d23ad7c863e92e28
        version: 0.10.1
        
