source 'https://supermarket.chef.io'

metadata

cookbook 'ccc', git: 'https://github.com/cheeseplus/ccc.git', branch: "updates"
cookbook 'wombat', path: '../wombat'
cookbook 'mock_data', path: 'test/fixtures/cookbooks/mock_data'
