name 'compliance'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures compliance'
long_description 'Installs/Configures compliance'
version '0.1.0'

depends 'apt'
depends 'ccc'
depends 'wombat'
