
---
driver:
  name: azurerm

driver_config:
  subscription_id: <%= ENV["AZURE_SUBSCRIPTION_ID"] %>
  location: 'westus2'
  machine_size: 'Standard_DS3_v2'

provisioner:
  name: chef_zero
  require_chef_omnibus: latest

verifier:
  name: inspec

platforms:
  - name: windows-2012r2
    driver_config:
      image_urn: MicrosoftWindowsServer:WindowsServer:2012-R2-Datacenter:latest
      os_type: windows
  - name: windows-2016
    driver_config:
      image_urn: MicrosoftWindowsServer:WindowsServer:2016-Datacenter:latest
      os_type: windows

suites:
  - name: default
    run_list:
      - recipe[mock_data]
      - recipe[workstation]
    attributes:
      chocolatey:
        upgrade: true
      demo:
        domain_prefix: ''
        domain: 'animals.biz'
        enterprise: 'mammals'
        org: 'marsupials'
        hosts:
        workstations: 1
        workstation-number: 1
        versions:
          chefdk: 'stable-latest'
