name 'workstation'
maintainer 'Team Wombat'
maintainer_email 'cheeseplus@chef.io'
license 'Apache 2.0'
description 'Configures a Windows workstation'
long_description 'Configures a Windows workstation'
version '0.4.2'
supports 'windows'

depends 'chocolatey'
depends 'windows'
depends 'hostsfile'
depends 'chef-ingredient'
depends 'wombat'
