name 'compliance'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures compliance'
long_description 'Installs/Configures compliance'
version '0.2.1'

depends 'ccc'
depends 'wombat'
depends 'line'
