source 'https://supermarket.chef.io'

metadata

cookbook 'delivery_build', git: "https://github.com/andrewelizondo/delivery_build"
cookbook 'delivery-base', git: "https://github.com/chef-cookbooks/delivery-base"
cookbook 'mock_data', path: 'test/fixtures/cookbooks/mock_data'
cookbook 'wombat', path: '../wombat'
